<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.analyzers" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Re.Shop.SharedKernel/Re.Shop.SharedKernel.csproj" />
    <ProjectReference Include="../../src/Re.Shop.Domain/Re.Shop.Domain.csproj" />
    <ProjectReference Include="../../src/Re.Shop.Application/Re.Shop.Application.csproj" />
    <ProjectReference Include="../../src/Re.Shop.Contracts/Re.Shop.Contracts.csproj" />
    <ProjectReference Include="../../src/Re.Shop.Infrastructure/Re.Shop.Infrastructure.csproj" />
    <ProjectReference Include="../../app/api/Re.Shop.Api.csproj" />
    <ProjectReference Include="../../app/admin/Re.Shop.Admin.csproj" />
  </ItemGroup>
</Project>